name: SERVER UPDATE

on:
  schedule:
    - cron: "0 8 * * *"
    - cron: "0 15 * * *"
    - cron: "50 23 * * *"
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-ohl-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy

      - name: Set Environment Variables
        run: |
          echo "SCHEDULE_API=${{ secrets.SCHEDULE_API }}" >> $GITHUB_ENV
          echo "PLAYERSTATS_API=${{ secrets.PLAYERSTATS_API }}" >> $GITHUB_ENV
          echo "ROSTERS_API=${{ secrets.ROSTERS_API }}" >> $GITHUB_ENV

      - name: Run Schedule Update Script
        env:
          SCHEDULE_API: ${{ env.SCHEDULE_API }}
        run: python get_2024_2025_schedule.py | tee -a workflow_summary.log
      
      - name: Run Player Stats Update Script
        env:
          PLAYERSTATS_API: ${{ env.PLAYERSTATS_API }}
        run: python get_ohl_stats.py | tee -a workflow_summary.log

      - name: Run Roster Update Script
        env:
          ROSTERS_API: ${{ env.ROSTERS_API }}
        run: python get_rosters.py | tee -a workflow_summary.log

      - name: Run Predictions Script
        run: python monte_carlo_sim.py | tee -a workflow_summary.log

      - name: Run Accuracy Check Script
        run: python accuracy_check.py | tee -a workflow_summary.log

      - name: Capture File Changes
        id: check_changes
        shell: bash
        run: |
          git add docs/OHL_SCHEDULE/*.csv docs/OHL_STATS/*.csv docs/OHL_ROSTERS/*.csv docs/JSON_DATA/*.json
          if git diff --cached --quiet; then
            echo "No changes detected."
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "changed=true" >> $GITHUB_ENV
          fi


      - name: Generate Summary
        run: |
          echo "## 📊 OHL Data Update Summary" > docs/JSON_DATA/workflow_summary.md
          echo "- **Workflow Execution Time:** $(date '+%Y-%m-%d %H:%M UTC')" >> docs/JSON_DATA/workflow_summary.md
          echo "- **Schedule Updated:** ✅" >> docs/JSON_DATA/workflow_summary.md
          echo "- **Player Stats Updated:** ✅" >> docs/JSON_DATA/workflow_summary.md
          echo "- **Rosters Updated:** ✅" >> docs/JSON_DATA/workflow_summary.md
          echo "- **Predictions Generated:** ✅" >> docs/JSON_DATA/workflow_summary.md
          echo "- **Accuracy Report Generated:** ✅" >> docs/JSON_DATA/workflow_summary.md
          if [[ "${{ env.changed }}" == "true" ]]; then
            echo "- **Updates Pushed to Repository:** ✅" >> docs/JSON_DATA/workflow_summary.md
          else
            echo "- **No Updates Needed:** No new data changes" >> docs/JSON_DATA/workflow_summary.md

      - name: Commit & Push Updates
        if: env.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/JSON_DATA/workflow_summary.md
          git commit -m "Automated OHL update summary for $(date '+%Y-%m-%d %H:%M UTC')"
          git push origin main
